do not commit generated protobuf code
haveno-dex/haveno-ui-poc pull request #37
Opened 2021-11-20 13:14 UTC by premek

generate it on `npm install` and `npm test`

2021-11-20 14:56 UTC, woodser approved these changes

2021-11-20 17:05 UTC, premek commented
- removed .proto files from this repo too, taken from `../../../haveno/proto/src/main/proto/*.proto` now
- updated the readme

Closes #38

2021-11-20 21:52 UTC, woodser commented
A problem is that IDEs can't find the derived files for development:

![image](https://user-images.githubusercontent.com/13068859/142741887-1a765bd7-e629-4d85-a486-e7ebe05737b0.png)

I'm thinking we should separate these PRs, one to build from the protobuf definitions in haveno, and one to automatically build the grpc client files if the above problem can be solved.

2021-11-20 21:53 UTC, woodser requested changes
See comment: https://github.com/haveno-dex/haveno-ui-poc/pull/37#issuecomment-974716597

2021-11-21 00:33 UTC, premek commented
does the ide not see it because it's not there (npm test or install didn't run yet) or because the directory is in gitignore now? (that shouldn't be a problem) or why?

2021-11-21 15:26 UTC, woodser commented
Ah yes that makes sense. :)

Opened a PR with some minor cleanup: https://github.com/premek/haveno-ui-poc/pull/2

(needs rebased on master)

2021-11-21 15:35 UTC, premek commented
rebased

2021-11-21 19:05 UTC, merged